# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PIP_2025_1_EQ_3\PIP_2025_1_EQ_3\Unidad 4\P2.1_Graficacion_Sensor\P1_Plantilla_Grafica.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(926, 683)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 161, 141))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/UAT LOGOS/Logo UAT.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(640, 0, 281, 211))
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/UAT LOGOS/logo facultad de ingenieria uat.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 330, 431, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_ColorLinea = QtWidgets.QComboBox(self.centralwidget)
        self.cb_ColorLinea.setGeometry(QtCore.QRect(502, 160, 141, 22))
        self.cb_ColorLinea.setObjectName("cb_ColorLinea")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 240, 55, 16))
        self.label_4.setObjectName("label_4")
        self.txt_titulo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_titulo.setGeometry(QtCore.QRect(130, 230, 113, 22))
        self.txt_titulo.setObjectName("txt_titulo")
        self.btn_titulo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_titulo.setGeometry(QtCore.QRect(250, 230, 93, 28))
        self.btn_titulo.setObjectName("btn_titulo")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(520, 130, 101, 20))
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(60, 280, 55, 16))
        self.label_15.setObjectName("label_15")
        self.btn_grilla = QtWidgets.QPushButton(self.centralwidget)
        self.btn_grilla.setGeometry(QtCore.QRect(120, 280, 93, 28))
        self.btn_grilla.setObjectName("btn_grilla")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 926, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Titulo"))
        self.btn_titulo.setText(_translate("MainWindow", "Establecer"))
        self.label_6.setText(_translate("MainWindow", "Color de la Linea:"))
        self.label_15.setText(_translate("MainWindow", "Grilla"))
        self.btn_grilla.setText(_translate("MainWindow", "OFF"))
import Recursos_rc
